name: agate
description: E-learning Platform
version: 1.1.0+2
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any

  # Localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Codegen
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Networking
  dio: ^5.4.3+1
  fresh_dio: ^0.4.1
  pretty_dio_logger: ^1.3.1

  # Persisting
  flutter_keychain: ^2.4.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1

  # Auth
  #  amplify_flutter: ^2.0.0
  #  amplify_auth_cognito: ^2.0.0
  #  amplify_authenticator: ^2.0.0
  #  firebase_core: ^2.31.1
  #  firebase_auth: ^4.20.0
  #  firebase_ui_auth: ^1.14.0
  #  google_sign_in: ^6.2.1
  #  firebase_ui_oauth_google: ^1.3.2

  # Utils
  go_router: ^14.1.3
  path_provider: ^2.1.3
  awesome_extensions: ^2.0.16
  easy_debounce: ^2.0.3
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  reactive_forms: ^17.0.1

  # UI
  flutter_image_slideshow: ^0.1.6
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  readmore: ^3.0.0
  endless: ^1.6.3
  chewie: ^1.8.1
  video_player: ^2.9.1
  ms_undraw:
    git:
      url: https://github.com/MahMoos/ms_undraw.git

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

  # Lints
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

  # Codegen
  freezed: ^2.5.2
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

  # Utils
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - shorebird.yaml

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon_transparent.png"
  adaptive_icon_background: #ffffff