// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_zfyDFi2lmnk1o6T7j2QvkcIXif6UK74',
    appId: '1:924971239933:web:7244d8e0b348cbe14b7194',
    messagingSenderId: '924971239933',
    projectId: 'qalam-center',
    authDomain: 'qalam-center.firebaseapp.com',
    storageBucket: 'qalam-center.appspot.com',
    measurementId: 'G-YBG71SKLMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRuPbVy_M-aUo3ZbcDPDx-_tmNAxKHi1I',
    appId: '1:924971239933:android:fda80a64616b55e24b7194',
    messagingSenderId: '924971239933',
    projectId: 'qalam-center',
    storageBucket: 'qalam-center.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPfQQEMluzMIx8fpbH3T9ydw0IoRENg0s',
    appId: '1:924971239933:ios:444d742bbba01bdb4b7194',
    messagingSenderId: '924971239933',
    projectId: 'qalam-center',
    storageBucket: 'qalam-center.appspot.com',
    iosClientId:
        '924971239933-up628i61tdna41p97nmj1cc9e1ur8cut.apps.googleusercontent.com',
    iosBundleId: 'com.mubtakerspace.agate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPfQQEMluzMIx8fpbH3T9ydw0IoRENg0s',
    appId: '1:924971239933:ios:568c40f1c0db04764b7194',
    messagingSenderId: '924971239933',
    projectId: 'qalam-center',
    storageBucket: 'qalam-center.appspot.com',
    iosClientId:
        '924971239933-j3tmsffct6roacil02fkjp2esjthjm6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
